version: '3.8'
services:
  db:
    image: postgres:13
    container_name: finance-app-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance-app
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
